### PR TITLE
Update to 3.4.1

### PR DESCRIPTION
**Pull request by rvalieris**

### CODE REVIEW

**Comment by rvalieris** [comment]
this is ready to merge I guess.

the appveyor build shows here as waiting, but it finished already.

**Comment by jdblischak** [comment]
Thanks @rvalieris! Could you please update [r-essentials](https://github.com/conda-forge/r-essentials-feedstock) next?

**Review by jdblischak — APPROVED** [review]

**Comment by rvalieris** [comment]
sure, once this is merged I will look into that.

**Comment by jdblischak** [comment]
@bgruening Please merge

**Comment by bgruening** [comment]
Wow, I'm confused and ashamed that we forgot to update this one as well.

**Comment by jdblischak** [comment]
> Wow, I'm confused and ashamed that we forgot to update this one as well.

@bgruening Don't be so hard on yourself! You do an awesome job with both conda-forge and bioconda. Besides this feedstock is easy to overlook since it's not an actual package but a bundle. @rvalieris has been tracking these down, and r-essentials should be the last bundle recipe.

**Comment by bgruening** [comment]
Thanks. Hope its working now.

**Comment by jdblischak** [comment]
The CircleCI issue was fixed by the empty PR you sent. Thanks! As long as the Travis and AppVeyor builds complete (they're currently queued, but there is no reason to suspect they won't build correctly), this feedstock will be updated for R 3.4.1.

**Pull request merged**
